// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConnectProtocol.proto

#ifndef PROTOBUF_ConnectProtocol_2eproto__INCLUDED
#define PROTOBUF_ConnectProtocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ConnectProtocol_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsParameterImpl();
void InitDefaultsParameter();
void InitDefaultsConnectProtocolImpl();
void InitDefaultsConnectProtocol();
inline void InitDefaults() {
  InitDefaultsParameter();
  InitDefaultsConnectProtocol();
}
}  // namespace protobuf_ConnectProtocol_2eproto
class ConnectProtocol;
class ConnectProtocolDefaultTypeInternal;
extern ConnectProtocolDefaultTypeInternal _ConnectProtocol_default_instance_;
class Parameter;
class ParameterDefaultTypeInternal;
extern ParameterDefaultTypeInternal _Parameter_default_instance_;

// ===================================================================

class Parameter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parameter) */ {
 public:
  Parameter();
  virtual ~Parameter();

  Parameter(const Parameter& from);

  inline Parameter& operator=(const Parameter& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Parameter(Parameter&& from) noexcept
    : Parameter() {
    *this = ::std::move(from);
  }

  inline Parameter& operator=(Parameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Parameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Parameter* internal_default_instance() {
    return reinterpret_cast<const Parameter*>(
               &_Parameter_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Parameter* other);
  friend void swap(Parameter& a, Parameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Parameter* New() const PROTOBUF_FINAL { return New(NULL); }

  Parameter* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Parameter& from);
  void MergeFrom(const Parameter& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Parameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:Parameter)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable int _cached_size_;
  friend struct ::protobuf_ConnectProtocol_2eproto::TableStruct;
  friend void ::protobuf_ConnectProtocol_2eproto::InitDefaultsParameterImpl();
};
// -------------------------------------------------------------------

class ConnectProtocol : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ConnectProtocol) */ {
 public:
  ConnectProtocol();
  virtual ~ConnectProtocol();

  ConnectProtocol(const ConnectProtocol& from);

  inline ConnectProtocol& operator=(const ConnectProtocol& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectProtocol(ConnectProtocol&& from) noexcept
    : ConnectProtocol() {
    *this = ::std::move(from);
  }

  inline ConnectProtocol& operator=(ConnectProtocol&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectProtocol& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectProtocol* internal_default_instance() {
    return reinterpret_cast<const ConnectProtocol*>(
               &_ConnectProtocol_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ConnectProtocol* other);
  friend void swap(ConnectProtocol& a, ConnectProtocol& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectProtocol* New() const PROTOBUF_FINAL { return New(NULL); }

  ConnectProtocol* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConnectProtocol& from);
  void MergeFrom(const ConnectProtocol& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConnectProtocol* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Parameter ParameterGroup = 20;
  int parametergroup_size() const;
  void clear_parametergroup();
  static const int kParameterGroupFieldNumber = 20;
  const ::Parameter& parametergroup(int index) const;
  ::Parameter* mutable_parametergroup(int index);
  ::Parameter* add_parametergroup();
  ::google::protobuf::RepeatedPtrField< ::Parameter >*
      mutable_parametergroup();
  const ::google::protobuf::RepeatedPtrField< ::Parameter >&
      parametergroup() const;

  // bytes ByteData = 21;
  void clear_bytedata();
  static const int kByteDataFieldNumber = 21;
  const ::std::string& bytedata() const;
  void set_bytedata(const ::std::string& value);
  #if LANG_CXX11
  void set_bytedata(::std::string&& value);
  #endif
  void set_bytedata(const char* value);
  void set_bytedata(const void* value, size_t size);
  ::std::string* mutable_bytedata();
  ::std::string* release_bytedata();
  void set_allocated_bytedata(::std::string* bytedata);

  // @@protoc_insertion_point(class_scope:ConnectProtocol)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Parameter > parametergroup_;
  ::google::protobuf::internal::ArenaStringPtr bytedata_;
  mutable int _cached_size_;
  friend struct ::protobuf_ConnectProtocol_2eproto::TableStruct;
  friend void ::protobuf_ConnectProtocol_2eproto::InitDefaultsConnectProtocolImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Parameter

// string Key = 1;
inline void Parameter::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Parameter::key() const {
  // @@protoc_insertion_point(field_get:Parameter.Key)
  return key_.GetNoArena();
}
inline void Parameter::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Parameter.Key)
}
#if LANG_CXX11
inline void Parameter::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Parameter.Key)
}
#endif
inline void Parameter::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Parameter.Key)
}
inline void Parameter::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Parameter.Key)
}
inline ::std::string* Parameter::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:Parameter.Key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Parameter::release_key() {
  // @@protoc_insertion_point(field_release:Parameter.Key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Parameter::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:Parameter.Key)
}

// string value = 2;
inline void Parameter::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Parameter::value() const {
  // @@protoc_insertion_point(field_get:Parameter.value)
  return value_.GetNoArena();
}
inline void Parameter::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Parameter.value)
}
#if LANG_CXX11
inline void Parameter::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Parameter.value)
}
#endif
inline void Parameter::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Parameter.value)
}
inline void Parameter::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Parameter.value)
}
inline ::std::string* Parameter::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:Parameter.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Parameter::release_value() {
  // @@protoc_insertion_point(field_release:Parameter.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Parameter::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:Parameter.value)
}

// -------------------------------------------------------------------

// ConnectProtocol

// repeated .Parameter ParameterGroup = 20;
inline int ConnectProtocol::parametergroup_size() const {
  return parametergroup_.size();
}
inline void ConnectProtocol::clear_parametergroup() {
  parametergroup_.Clear();
}
inline const ::Parameter& ConnectProtocol::parametergroup(int index) const {
  // @@protoc_insertion_point(field_get:ConnectProtocol.ParameterGroup)
  return parametergroup_.Get(index);
}
inline ::Parameter* ConnectProtocol::mutable_parametergroup(int index) {
  // @@protoc_insertion_point(field_mutable:ConnectProtocol.ParameterGroup)
  return parametergroup_.Mutable(index);
}
inline ::Parameter* ConnectProtocol::add_parametergroup() {
  // @@protoc_insertion_point(field_add:ConnectProtocol.ParameterGroup)
  return parametergroup_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Parameter >*
ConnectProtocol::mutable_parametergroup() {
  // @@protoc_insertion_point(field_mutable_list:ConnectProtocol.ParameterGroup)
  return &parametergroup_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Parameter >&
ConnectProtocol::parametergroup() const {
  // @@protoc_insertion_point(field_list:ConnectProtocol.ParameterGroup)
  return parametergroup_;
}

// bytes ByteData = 21;
inline void ConnectProtocol::clear_bytedata() {
  bytedata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectProtocol::bytedata() const {
  // @@protoc_insertion_point(field_get:ConnectProtocol.ByteData)
  return bytedata_.GetNoArena();
}
inline void ConnectProtocol::set_bytedata(const ::std::string& value) {
  
  bytedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectProtocol.ByteData)
}
#if LANG_CXX11
inline void ConnectProtocol::set_bytedata(::std::string&& value) {
  
  bytedata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectProtocol.ByteData)
}
#endif
inline void ConnectProtocol::set_bytedata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bytedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectProtocol.ByteData)
}
inline void ConnectProtocol::set_bytedata(const void* value, size_t size) {
  
  bytedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectProtocol.ByteData)
}
inline ::std::string* ConnectProtocol::mutable_bytedata() {
  
  // @@protoc_insertion_point(field_mutable:ConnectProtocol.ByteData)
  return bytedata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectProtocol::release_bytedata() {
  // @@protoc_insertion_point(field_release:ConnectProtocol.ByteData)
  
  return bytedata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectProtocol::set_allocated_bytedata(::std::string* bytedata) {
  if (bytedata != NULL) {
    
  } else {
    
  }
  bytedata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bytedata);
  // @@protoc_insertion_point(field_set_allocated:ConnectProtocol.ByteData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ConnectProtocol_2eproto__INCLUDED
